name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d -u github.com/spf13/cobra/cobra |
	      go get -v -t -d -u github.com/jstemmer/go-junit-report |
	      go get -v -t -d -u github.com/inconshreveable/mousetrap |
	      go get -v -t -d -u github.com/mitchellh/go-homedir |
        go get -v -t -d -u github.com/t-yuki/gocover-cobertura |
	      go get -v -t -d -u golang.org/x/lint/golint |

    - name: Build
      run: go build -v -ldflags="-X main.version=$(shell git describe --always --long --dirty)" -o bin/pull-task cmd/pull-task/main.go

    - name: Test
      run: go test -v ./...
